language: go
env:
  - DB_USER=postgres
  - DB_TEST_DB=test_gitstreams
services:
  - postgres
before_script:
  - psql -c 'create database test_gitstreams;' -U postgres
install: echo "dependencies are checked in. Skipping install."
script: GOPATH=$PWD:$GOPATH go test gitstreams
