language: go
env:
  - DB=postgres
before_script:
  - psql -c 'create database test_gitstreams;' -U postgres
  - psql -c '\i ./schema.sql'
install: echo "dependencies are checked in. Skipping install."
script: DB_USER=postgres DB_TEST_DB=test_gitstreams GOPATH=$PWD:$GOPATH go test gitstreams
